-- Migration number: 0001 	 2026-09-10T23:16:42.885Z

CREATE TABLE IF NOT EXISTS Song (
	SongId			INTEGER PRIMARY KEY AUTOINCREMENT,
	SongName		TEXT NOT NULL,
	ComposerId		INTEGER NOT NULL,
	AddVersion		TEXT NOT NULL,
	ChapterId		INTEGER NOT NULL,
	FOREIGN KEY (ComposerId) REFERENCES Composer(ComposerId),
	FOREIGN KEY (ChapterId) REFERENCES Chapter(ChapterId)
);
CREATE TABLE IF NOT EXISTS Composer (
	ComposerId		INTEGER PRIMARY KEY AUTOINCREMENT,
	ComposerName	TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS Chapter (
	ChapterId		INTEGER PRIMARY KEY AUTOINCREMENT,
	ChapterName		TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS Chart (
	ChartId			INTEGER PRIMARY KEY AUTOINCREMENT,
	SongId			INTEGER NOT NULL,
	DiffDZ			TEXT,
	DiffSK			TEXT,
	DiffCB			TEXT,
	DiffCL			TEXT,
	DiffSP			TEXT,
	NoteDZ			TEXT,
	NoteSK			TEXT,
	NoteCB			TEXT,
	NoteCL			TEXT,
	NoteSP			TEXT,
	FOREIGN KEY (SongId) REFERENCES Song(SongId)
);
