INSERT INTO Composer (ComposerName) VALUES ("TsukiP");
INSERT INTO Composer (ComposerName) VALUES ("Delos");
INSERT INTO Composer (ComposerName) VALUES ("CrLrisEto");
INSERT INTO Composer (ComposerName) VALUES ("B.R.I");
INSERT INTO Composer (ComposerName) VALUES ("Gray Planet");
INSERT INTO Composer (ComposerName) VALUES ("LeaF");
INSERT INTO Composer (ComposerName) VALUES ("Reo、ヒトリ (lyric: 霉霉杏)");
INSERT INTO Composer (ComposerName) VALUES ("MoryueCi");
INSERT INTO Composer (ComposerName) VALUES ("黑瘦的鱼头");
INSERT INTO Composer (ComposerName) VALUES ("A-39＆沙包P");
INSERT INTO Composer (ComposerName) VALUES ("t+pazolite");
INSERT INTO Composer (ComposerName) VALUES ("Kuroe");
INSERT INTO Composer (ComposerName) VALUES ("Joulez");
INSERT INTO Composer (ComposerName) VALUES ("Reku Mochizuki");
INSERT INTO Composer (ComposerName) VALUES ("ShooTinGStaR + xzadudu179 + MoryueCi + Cyberspace");
INSERT INTO Composer (ComposerName) VALUES ("James Primate & Lydia Esrig");
INSERT INTO Composer (ComposerName) VALUES ("SJQ音福");
INSERT INTO Composer (ComposerName) VALUES ("影虎。");
INSERT INTO Composer (ComposerName) VALUES ("ああああ");
INSERT INTO Composer (ComposerName) VALUES ("ILusMin");
INSERT INTO Composer (ComposerName) VALUES ("AiSS");
INSERT INTO Composer (ComposerName) VALUES ("Kirara Magic");
INSERT INTO Composer (ComposerName) VALUES ("Function Phantom");
INSERT INTO Composer (ComposerName) VALUES ("有棵里里");
INSERT INTO Composer (ComposerName) VALUES ("SharK");
INSERT INTO Composer (ComposerName) VALUES ("U-Ruri");
INSERT INTO Composer (ComposerName) VALUES ("Wooden, Salty Salt");
INSERT INTO Composer (ComposerName) VALUES ("AiSS vs. Abit");
INSERT INTO Composer (ComposerName) VALUES ("HLxQ.v.M");
INSERT INTO Composer (ComposerName) VALUES ("X3ll3n");
INSERT INTO Composer (ComposerName) VALUES ("如月青蘭 feat.双葉湊音");
INSERT INTO Composer (ComposerName) VALUES ("PYKAMIA");
INSERT INTO Composer (ComposerName) VALUES ("RyosU feat.茶茶");
INSERT INTO Composer (ComposerName) VALUES ("Villax vs. Amberry");
INSERT INTO Composer (ComposerName) VALUES ("Sobrem");
INSERT INTO Composer (ComposerName) VALUES ("SuggestedCopy7 & 亚述");
INSERT INTO Composer (ComposerName) VALUES ("Zris feat. Katie");
INSERT INTO Composer (ComposerName) VALUES ("Silentroom");
INSERT INTO Composer (ComposerName) VALUES ("Cansol");
INSERT INTO Composer (ComposerName) VALUES ("Fl00t");
INSERT INTO Composer (ComposerName) VALUES ("Halv");
INSERT INTO Composer (ComposerName) VALUES ("James Primate");
INSERT INTO Composer (ComposerName) VALUES ('Connor "12LBS" Skidmore');
INSERT INTO Composer (ComposerName) VALUES ('James Primate, Lydia Esrig, Connor "12LBS" Skidmore');
INSERT INTO Composer (ComposerName) VALUES ("Lydia Esrig");
INSERT INTO Composer (ComposerName) VALUES ("10lulu");
INSERT INTO Composer (ComposerName) VALUES ("むさぬりゆ");
INSERT INTO Composer (ComposerName) VALUES ("MYUKKE.");
INSERT INTO Composer (ComposerName) VALUES ("Kaede Hiyama (MoryueCi Mix)");
INSERT INTO Composer (ComposerName) VALUES ("ME_DD");
INSERT INTO Composer (ComposerName) VALUES ("Euphem1a.");
INSERT INTO Composer (ComposerName) VALUES ("Nerovix");
INSERT INTO Composer (ComposerName) VALUES ("R-TOP");
INSERT INTO Composer (ComposerName) VALUES ("K1N");
INSERT INTO Composer (ComposerName) VALUES ("溝口ゆうま feat. 大瀬良あい");
INSERT INTO Composer (ComposerName) VALUES ("Otokaze");
INSERT INTO Composer (ComposerName) VALUES ("PYKAMIA VS Sakuzyo");
INSERT INTO Composer (ComposerName) VALUES ("ILusMin feat. Bob Hou");
INSERT INTO Composer (ComposerName) VALUES ("DRIVE.");
INSERT INTO Composer (ComposerName) VALUES ("MMQX");
INSERT INTO Composer (ComposerName) VALUES ("Tanchiky");
INSERT INTO Composer (ComposerName) VALUES ("MYTK");
INSERT INTO Composer (ComposerName) VALUES ("Dragon_Klub");
INSERT INTO Composer (ComposerName) VALUES ("テヅカ");
INSERT INTO Composer (ComposerName) VALUES ("NceS & All_Life_X & AiSS");
INSERT INTO Composer (ComposerName) VALUES ("Tatsunoshin");
INSERT INTO Composer (ComposerName) VALUES ("Vantasy");
INSERT INTO Composer (ComposerName) VALUES ("SQRY01");
INSERT INTO Composer (ComposerName) VALUES ("Wooden");
INSERT INTO Composer (ComposerName) VALUES ("世界の花");
INSERT INTO Composer (ComposerName) VALUES ("PYKAMIA vs Reku Mochizuki");
INSERT INTO Composer (ComposerName) VALUES ("BilliumMoto");
INSERT INTO Composer (ComposerName) VALUES ("siromaru + cranky");
INSERT INTO Composer (ComposerName) VALUES ("初云CLoudie");
INSERT INTO Composer (ComposerName) VALUES ("Yooh");
INSERT INTO Composer (ComposerName) VALUES ("Rigel Wired");
INSERT INTO Composer (ComposerName) VALUES ("t404:null");
INSERT INTO Composer (ComposerName) VALUES ("ADA");
INSERT INTO Composer (ComposerName) VALUES ("Lalot. vs Night Yard");
INSERT INTO Composer (ComposerName) VALUES ("gmtn.(witch's slave)");
INSERT INTO Composer (ComposerName) VALUES ("PYKAMIA vs. ルゼ");
INSERT INTO Composer (ComposerName) VALUES ("Laur vs CK");
INSERT INTO Composer (ComposerName) VALUES ("TRIAL");
INSERT INTO Composer (ComposerName) VALUES ("Hammer Switch");
INSERT INTO Composer (ComposerName) VALUES ("一万年老海妖");
INSERT INTO Composer (ComposerName) VALUES ("Natunoruno");
INSERT INTO Composer (ComposerName) VALUES ("Antistar feat. Ctymax");
INSERT INTO Composer (ComposerName) VALUES ("Ocelot");
INSERT INTO Composer (ComposerName) VALUES ("Se-U-Ra");
INSERT INTO Composer (ComposerName) VALUES ("uma");
INSERT INTO Composer (ComposerName) VALUES ("onoken");
INSERT INTO Composer (ComposerName) VALUES ("ryhki");
INSERT INTO Composer (ComposerName) VALUES ("Lifetheory");
INSERT INTO Composer (ComposerName) VALUES ("Lime");
