INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Welcome to Milthm", 1, "1.0", 2);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Episodic Rain", 2, "1.0", 2);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Castle in the Rain", 3, "1.0", 3);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Jump out?", 4, "1.0", 3);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Blueface", 5, "1.0", 3);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("イコラト", 1, "1.0", 3);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("雨女", 1, "1.0", 3);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("命日", 6, "1.0", 3);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("ネオン色のまち feat. Mai", 7, "1.0", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("INFP.mp3", 1, "1.0", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Oniichan", 8, "1.0", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Oiiaioooooiai", 9, "1.0", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("WATER", 10, "1.1", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Dogbite", 11, "1.1", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Hikari", 12, "1.2", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("夜風", 13, "1.3", 2);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Moonflutter", 14, "1.3", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Fly To Meteor (Milthm Edit)", 15, "1.5", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Sundown", 16, "1.6", 4);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Bio-Enfineering", 16, "1.6", 4);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Threat - Sky Islands", 16, "1.6", 4);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Threat - Superstructure", 16, "1.6", 4);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("A Reincarnation of Scattering spring", 17, "1.7", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Innocent white", 18, "1.9", 5);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("cybernetic blazar", 19, "1.9", 5);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Sparkrain", 20, "1.9", 5);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Agnostic", 21, "1.10", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("花月", 22, "1.10", 2);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Future Unbound (Game Edit)", 13, "1.11", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Psyched Fevereiro", 11, "1.11", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Algebra", 23, "1.12", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Thick Rain", 24, "2.0", 6);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Aconsma", 20, "2.0", 6);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("OverRain", 25, "2.0", 6);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Fragment of Memories", 26, "2.0", 6);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("HYPER MEMORIES", 27, "2.0", 6);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Regnaissance", 28, "2.0", 6);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Contrasty Angeles", 29, "2.0", 6);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Words", 30, "2.1", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("仮想明日", 31, "2.1", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("白虎蓮華", 32, "2.2", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Reminiscence in Starlight", 33, "2.3", 2);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("サイクルの欠片", 1, "2.3", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("参宿四~Betelgeuse~", 34, "2.3", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("slic.hertz #GdbG", 35, "2.3", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Rainbow Flavor!", 36, "2.4", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("IN", 37, "2.4", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("驟雨の狭間", 38, "3.0", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Broken Conviction", 39, "3.1", 1);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Elsorhg", 40, "3.2", 5);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Meltovt Necrosys", 41, "3.2", 5);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Kayava", 42, "3.3", 4);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Threat - Metropolis", 43, "3.3", 4);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Threat - Waterfront Complex", 44, "3.3", 4);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("White Lizard", 45, "3.3", 4);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Sheer Ice Torrent", 43, "3.3", 4);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("大月墜落狂想", 46, "3.3", 4);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("cafe in 6412I731V", 47, "3.4", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("FULi AUTO SHOOTER", 48, "3.4", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("KASANE", 49, "3.5", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Fantasia Sonata Sky Syndrome", 32, "3.6", 2);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Fantasia Sonata Stars", 32, "3.6", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("はんてん", 50, "3.7", 8);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("apOapSis (Edit)", 51, "3.7", 8);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Virtual S0da", 52, "3.7", 8);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Curse of 14", 53, "3.7", 8);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("LOUDER!", 54, "3.8", 3);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Brightened Demonios", 29, "3.8", 6);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Myth compiler", 55, "3.8", 6);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Fantasia Sonata Arcadia", 32, "3.8", 6);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("ホシフルヨルニ", 56, "3.9", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Fantasia Sonata God Dance", 57, "3.9", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("GlassyHeart.", 58, "3.10", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Chartreuse Green", 11, "3.10", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Aleph-0", 6, "3.11", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Vestige of Dreams", 59, "4.0", 9);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("百九十", 60, "4.0", 9);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("灯ノ桜蝶", 61, "4.0", 9);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Sakuyahime", 62, "4.0", 9);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("靈", 62, "4.0", 9);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("BUCHiAGE Fireworks", 63, "4.0", 9);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("ニニ (feat. Qayo & mii)", 64, "4.0", 9);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Garden", 65, "4.0", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Fantasia Sonata Botanical Garden", 32, "4.0", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Dum! Dum!! Dum!!!", 66, "4.0", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Splash the Beat!!", 19, "4.0", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Fantasia Sonata Reflection", 32, "4.0", 2);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Autumn Rain", 67, "4.1", 10);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Pthahnil", 21, "4.1", 10);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Deluge", 68, "4.1", 10);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Fluorescent Light", 69, "4.1", 10);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("いつか忘れるんだろう", 1, "4.2", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("運命", 70, "4.2", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Fantasia Sonata Hope", 71, "4.2", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Before it Ends", 72, "4.2", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("conflict", 73, "4.3", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Sound of Nature", 74, "4.3", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Melody to Heaven", 26, "4.4", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("LiFE Garden/LiFE Garden (Extended Mix)", 75, "4.4", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Polyridia", 76, "4.5", 10);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Ephemeric World", 77, "4.5", 10);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Habitable zone", 78, "5.0", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("烽閻鸞錵", 79, "5.0", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("furioso melodia", 80, "5.1", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Fantasia Sonata Surmount Vanity Aufleben", 81, "5.1", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Lost Civilization", 82, "5.2", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Imouto", 83, "5.2", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Lots Of Spices", 84, "5.2", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("九蓮寶燈", 85, "5.3", 10);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("白色の夢で。", 86, "5.3", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Class Memories", 87, "5.3", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("KAEDE", 88, "5.3", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("DEAR", 56, "6.0", 11);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Rustala", 89, "6.0", 11);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Recall Memories", 90, "6.0", 11);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("ヘリオトロープ(feat. NIQRO)", 91, "6.0", 11);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Tales of Misery", 92, "6.0", 11);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Σquinoχ(Equinox)", 78, "6.0", 11);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Daisy", 93, "6.0", 7);
INSERT INTO Song (SongName, ComposerId, AddVersion, ChapterId) VALUES ("Tsukuyomi", 94, "6.0", 7);
