-- Migration number: 0001 	 2026-03-25T04:26:00.779Z

-- テーブル作成
CREATE TABLE IF NOT EXISTS Song (
	SongId			INTEGER PRIMARY KEY AUTOINCREMENT,
	SongName		TEXT NOT NULL,
	ComposerId		INTEGER NOT NULL,
	Bpm				INTEGER NOT NULL,
	SongLength		INTEGER NOT NULL,
	AddVersion		TEXT NOT NULL,
	ChapterId		INTEGER NOT NULL,
	FOREIGN KEY (ComposerId) REFERENCES Composer(ComposerId),
	FOREIGN KEY (ChapterId) REFERENCES Chapter(ChapterId)
);
CREATE TABLE IF NOT EXISTS Composer (
	ComposerId		INTEGER PRIMARY KEY AUTOINCREMENT,
	ComposerName	TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS Chapter (
	ChapterId		INTEGER PRIMARY KEY AUTOINCREMENT,
	ChapterName		TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS Chart (
	ChartId			INTEGER PRIMARY KEY AUTOINCREMENT,
	SongId			INTEGER NOT NULL,
	DiffEZ			INTEGER NOT NULL,
	DiffHD			INTEGER NOT NULL,
	DiffIN			INTEGER NOT NULL,
	DiffAT			INTEGER,
	NoteEZ			INTEGER NOT NULL,
	NoteHD			INTEGER NOT NULL,
	NoteIN			INTEGER NOT NULL,
	NoteAT			INTEGER,
	FOREIGN KEY (SongId) REFERENCES Song(SongId)
);

