INSERT INTO Chapter (ChapterName) VALUES ("Single シングル精選集");
INSERT INTO Chapter (ChapterName) VALUES ("Legacy 過去の章");
INSERT INTO Chapter (ChapterName) VALUES ("Chapter 5 ネオンサイン");
INSERT INTO Chapter (ChapterName) VALUES ("Chapter 6 方舟の蜃気楼");
INSERT INTO Chapter (ChapterName) VALUES ("Chapter 7 クロネクション");
INSERT INTO Chapter (ChapterName) VALUES ("Chapter 8 朔月の汐");
INSERT INTO Chapter (ChapterName) VALUES ("Side story 1 ロートス");
INSERT INTO Chapter (ChapterName) VALUES ("Side story 2 滅の日");
INSERT INTO Chapter (ChapterName) VALUES ("Side story 3 盗楽行");
INSERT INTO Chapter (ChapterName) VALUES ("Side story 4 無相郷");
INSERT INTO Chapter (ChapterName) VALUES ("Rising Sun Traxx 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("HyuN 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("GOOD 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("WAVEAT 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("Muse Dash 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("KALPA 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("Lanota 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("姜米條 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("茶鸣拾贰律 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("OverRapid 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("かめりあ 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("Rotaeno 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("CHUNITHM 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("Paradigm:Reboot 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("SHINOBI SLASH 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("TAKUMI³ 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("节奏大师 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("EGTS 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("Immaculée Sekai 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("オンゲキ 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("maimai でらっくす 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("Liminality 精選集");
INSERT INTO Chapter (ChapterName) VALUES ("Cytus II 精選集");
