INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Glaciaxion", 1, 140, 163, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Eradication Catastrophe", 2, 120, 127, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Credits", 3, 179, 101, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Dlyrotz", 4, 175, 122, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Engine x start!! (melody mix)", 5, 186, 92, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("光", 6, 180, 132, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Winter ↑ cube ↓", 7, 104, 156, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Cipher : \2&\\<|0", 8, 179, 154, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("混乱-Confusion", 9, 180, 128, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("FULi AUTO SHOOTER", 10, 145, 130, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("HumaN", 11, 180, 134, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("[PRAW]", 12, 210, 157, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Pixel Rebelz", 13, 150, 143, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Cereris", 14, 175, 168, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Non-Melodic Ragez (MUG Edit)", 13, 205, 139, "1.0.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Sultan Rage", 15, 155, 114, "1.1.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Class Memories", 16, 145, 147, "1.1.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("-SURREALISM-", 17, 180, 154, "1.1.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Bonus Time", 18, 180, 115, "1.1.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("ENERGY SYNERGY MATRIX", 19, 160, 125, "1.1.0", 2);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("NYA!!! (Phigros ver.)", 20, 154, 156, "1.3.0", 3);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("JunXion Between Life And Death (VIP Mix)", 21, 164, 143, "1.3.0", 3);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("cryout", 22, 180, 126, "1.3.0", 3);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Reimei", 23, 185, 146, "1.3.0", 3);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("尊師 ~The Guru~", 24, 152, 129, "1.3.0", 3);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Spasmodic", 25, 200, 155, "1.3.0", 3);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Leave All Behind", 24, 150, 127, "1.4.6", 3);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Colorful Days♪", 26, 136, 100, "1.5.0", 4);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("micro.wav", 27, 172, 122, "1.5.0", 4);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("重生", 6, 195, 143, "1.5.0", 4);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("NO ONE YES MAN", 10, 170, 127, "1.5.0", 4);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("望影の方舟Six", 28, 209, 113, "1.5.0", 4);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Igallta", 28, 230, 122, "1.5.0", 4);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Clock Paradox", 29, 140, 150, "2.0.0", 5);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Chronologika", 30, 180, 134, "2.0.0", 5);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Nick of Time", 31, 175, 142, "2.0.0", 5);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Chronomia", 32, 227, 146, "2.0.0", 5);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Chronos Collapse - La Campanella", 1, 180, 153, "2.0.0", 5);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Rrhar'il", 33, 190, 132, "2.0.0", 5);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Crave Wave", 34, 150, 127, "3.0.0", 6);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("The Chariot ~ REVIIVAL~", 35, 190, 146, "3.0.0", 6);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Luminescence", 36, 184, 154, "3.0.0", 6);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Retribution", 37, 190, 157, "3.0.0", 6);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("DESTRUCTION 3,2,1", 38, 321, 160, "3.0.0", 6);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Distorted Fate", 39, 150, 162, "3.0.0", 6);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Ποσειδών", 40, 175, 123, "1.6.0", 7);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("WATER", 41, 170, 157, "1.6.0", 7);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Miracle Forest (VIP Mix)", 42, 192, 170, "1.6.0", 7);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("MOBILYS", 43, 144, 163, "1.6.0", 7);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Lyrith -迷宮リリス-", 44, 177, 147, "1.6.0", 7);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Demiurge", 45, 111, 168, "2.1.3", 8);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Demonkin", 46, 192, 138, "2.2.0", 8);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Re_Nascence (Psystyle Ver.)", 42, 150, 147, "2.2.0", 8);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Ark", 47, 180, 163, "2.2.0", 8);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("After Dawn", 48, 110, 138, "2.2.0", 8);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("INFiNiTE ENERZY -Overdoze-", 49, 180, 120, "2.2.0", 8);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Khalid", 50, 128, 132, "3.5.0", 9);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Quantum Hyperspace", 51, 200, 125, "3.5.0", 9);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Freaky Undulations ~Noble Knights of Tune~", 52, 202, 137, "3.5.0", 9);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("PANIC PARADISE", 53, 170, 128, "3.5.0", 9);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Re: End of a Dream", 54, 212, 141, "3.5.0", 9);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("心の記憶", 41, 150, 165, "3.9.0", 10);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Spotlight", 55, 160, 129, "3.9.0", 10);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("NightTheater", 56, 151, 120, "3.9.0", 10);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Ramification", 57, 175, 137, "3.9.0", 10);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Der Richter", 58, 192, 147, "3.9.0", 10);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("ATHAZA", 59, 280, 162, "3.9.0", 10);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Doppelganger", 59, 280, 145, "1.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("もぺもぺ", 59, 100, 110, "1.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("MARENOL", 59, 140, 127, "1.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("萤火虫の怨", 60, 100, 158, "1.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("万吨匿名信", 60, 120, 165, "1.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("风屿", 60, 170, 179, "1.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("dB doll", 61, 128, 108, "1.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Dash", 62, 128, 114, "1.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("云女孩", 63, 155, 178, "1.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Drop It", 64, 126, 203, "1.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("RIPPER", 65, 150, 199, "1.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Aphasia", 60, 128, 116, "1.2.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("开心病", 60, 131, 115, "1.2.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("華灯爱", 60, 120, 113, "1.2.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Find_Me", 66, 191, 128, "1.2.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Sein", 67, 210, 119, "1.2.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("狂喜蘭舞", 59, 230, 162, "1.2.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Sparkle New Life", 24, 150, 138, "1.2.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Khronostasis Katharsis", 68, 188, 135, "1.2.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Snow Desert", 29, 125, 143, "1.2.4", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Burn", 2, 148, 138, "1.2.4", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Aleph-0", 59, 400, 141, "1.2.5", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Next Time", 69, 175, 111, "1.3.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Rubbish Sorting", 70, 128, 166, "1.3.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Another Me", 71, 175, 140, "1.4.0", 11);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("mechanted", 72, 172, 116, "1.4.0", 11);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("life flashes before weeb eyes", 73, 227, 157, "1.4.0", 11);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Break Through The Barrier", 74, 176, 132, "1.4.0", 11);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Chronostasis", 75, 196, 143, "1.4.0", 11);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Dead Soul", 76, 132, 147, "1.4.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Infinity Heaven", 77, 160, 155, "1.4.2", 12);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Disorder", 78, 193, 134, "1.4.2", 12);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("CROSS†SOUL", 79, 200, 139, "1.4.2", 12);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Speed Up!", 80, 145, 141, "1.4.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Magenta Potion", 81, 150, 147, "1.4.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Get Back", 82, 128, 144, "1.4.4", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Palescreen", 83, 173, 146, "1.4.5", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("GOODTEK", 84, 190, 126, "1.4.7", 13);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("GOODBOUNCE", 84, 180, 133, "1.4.7", 13);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("GOODWORLD", 84, 165, 132, "1.4.7", 13);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("GOODFORTUNE", 84, 170, 133, "1.4.7", 13);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("GOODRAGE", 84, 222, 122, "1.4.7", 13);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("The Mountain Eater", 85, 127, 150, "1.5.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Orthodox", 86, 170, 141, "1.5.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("End Me", 87, 120, 130, "1.5.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Parallel Retrogression(Game Ver.)", 88, 175, 143, "1.5.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Starduster", 89, 220, 130, "1.5.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Electron", 90, 128, 129, "1.5.7", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("SIGMA", 91, 200, 121, "1.5.7", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Hardcore Kwaya", 92, 200, 121, "1.6.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Äventyr", 93, 132, 160, "1.6.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Träne", 94, 135, 147, "1.6.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("雪降り、メリクリ", 95, 180, 158, "1.6.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Cervelle Connexion", 96, 142, 150, "1.6.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("modulus", 97, 158, 120, "1.6.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Wavetapper", 3, 112, 162, "1.6.5", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("大和撫子 -Wild Dances-", 98, 158, 128, "1.6.6", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Eltaw", 99, 193, 136, "1.6.6", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Initialize", 100, 128, 131, "1.6.7", 14);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("桜樹街道", 101, 135, 144, "1.6.7", 14);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Get Ready!!", 100, 142, 130, "1.6.7", 14);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("volcanic", 102, 382, 137, "1.6.7", 14);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Better Graphic Animation", 103, 180, 102, "1.6.7", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("XING", 104, 177, 130, "1.6.8", 15);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Final Step!", 32, 180, 133, "1.6.8", 15);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Cthugha", 105, 213, 154, "1.6.8", 15);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("With You", 106, 175, 126, "1.6.9", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Unorthodox Thoughts", 107, 146, 144, "1.6.9", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Apocalyptic", 108, 160, 129, "1.6.10", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("游园地", 109, 128, 128, "1.6.10", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("energy trixxx", 110, 160, 145, "1.6.11", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Nhelv", 111, 174, 159, "2.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("-Arkhei-", 112, 112, 157, "2.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Kerberos", 113, 197, 128, "2.0.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("ρars/ey", 114, 180, 124, "2.0.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Concvssion", 68, 190, 152, "2.1.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("ジングルベル(Jingle Bell)", 41, 176, 168, "2.1.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Time to Night Sky (feat. Lee Yu Jin)", 115, 128, 131, "2.1.0", 16);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("HAZARD", 116, 128, 127, "2.1.0", 16);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Another Me", 51, 210, 168, "2.1.0", 16);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Don't Never Around", 117, 175, 119, "2.1.0", 16);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("RESSiSTANCE", 118, 205, 149, "2.1.0", 16);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Dreamland", 119, 120, 159, "2.1.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Another Round", 120, 128, 152, "2.1.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("996", 121, 140, 154, "2.1.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Future Mind", 122, 180, 134, "2.1.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Luminescent", 123, 141, 156, "2.1.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("FULi AUTO BUSTER", 10, 145, 126, "2.1.4", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("I Must Say No", 124, 175, 116, "2.2.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("opia", 125, 193, 148, "2.2.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Apocalypse", 126, 220, 163, "2.3.0", 17);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Protoflicker", 111, 140, 167, "2.3.0", 17);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Horizon Blue", 127, 200, 165, "2.3.0", 17);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("You are the Miserable", 128, 163, 164, "2.3.0", 17);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Stasis", 129, 180, 155, "2.3.0", 17);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("いざ、参ります", 130, 188, 163, "2.3.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("月下缭乱", 131, 175, 150, "2.3.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("On And On!!", 132, 170, 122, "2.3.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("DataErrOr", 133, 180, 125, "2.4.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Shadow", 134, 172, 143, "1.6.4", 18);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("心之所向", 6, 180, 137, "2.4.0", 18);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("inferior", 6, 200, 125, "2.4.0", 18);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("c.s.q.n.", 135, 174, 125, "2.4.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Brave Notes", 136, 192, 118, "2.4.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("盏茗", 137, 131, 130, "2.4.2", 19);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("青芽", 137, 216, 135, "2.4.2", 19);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Eternal Snow", 138, 140, 155, "2.4.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Rainy Season", 138, 188, 114, "2.4.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("El Condor Pasa (Phigros Edit)", 139, 150, 132, "2.4.4", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Break Over", 66, 185, 128, "2.4.4", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Believe Light (feat. 果丸哒呦)", 140, 150, 170, "2.4.5", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Pont des souvenirs", 141, 185, 165, "2.4.5", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("青丘", 142, 180, 168, "2.4.6", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("瓷岁", 137, 126, 166, "2.4.7", 19);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Feast远东之宴", 137, 128, 150, "2.4.7", 19);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("インフェルノシティ", 143, 215, 124, "2.5.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Upshift", 144, 155, 141, "2.5.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Poison AND÷OR Affection", 59, 120, 125, "2.5.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Random", 145, 132, 137, "2.5.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("零號車輛", 146, 240, 141, "2.5.1", 24);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Now Is The Time, Do It", 147, 158, 133, "3.0.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Bougainvillea", 148, 120, 122, "3.0.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("神話", 149, 130, 138, "3.1.0", 20);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("El último baile", 150, 175, 123, "3.1.0", 20);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Trojan", 151, 128, 152, "3.1.0", 20);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Temporal Shifting", 152, 155, 140, "3.1.0", 20);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Ad astra per aspera", 153, 197, 144, "3.1.0", 20);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("A journey to the moonlight", 154, 174, 150, "3.1.0", 20);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Rainy Heart", 155, 140, 155, "3.1.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Realms", 156, 174, 128, "3.1.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("ぱぴぷぴぷぴぱ", 157, 200, 178, "3.1.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Triumph & Regret", 158, 175, 124, "3.1.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("S.A.T.E.L.L.I.T.E.", 159, 150, 190, "3.2.0", 21);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Dance with Silence", 159, 128, 179, "3.2.0", 21);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Labyrinth in Kowloon: Walled World", 159, 190, 180, "3.2.0", 21);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Compute It With Some Devilish Alcoholic Steampunk Engines", 159, 165, 172, "3.2.0", 21);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("+ERABY+E CONNEC+10N", 159, 230, 167, "3.2.0", 21);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Diamond Eyes", 160, 140, 134, "3.2.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Bitterblossom", 161, 180, 144, "3.2.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Silence is Golden, Speech is Golden", 162, 177, 166, "3.2.2", 28);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Fractured Angel", 163, 301, 183, "3.2.2", 28);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Journey with You", 164, 150, 129, "3.3.0", 22);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Secret Illumination", 165, 160, 150, "3.3.0", 22);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Inverted World", 166, 180, 132, "3.3.0", 22);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("月詠に鳴る", 167, 180, 135, "3.9.0", 23);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("TECHNOPOLIS 2085", 168, 134, 140, "3.4.0", 23);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("祈 -我ら神祖と共に歩む者なり-", 169, 270, 180, "3.4.0", 23);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("bye", 170, 160, 160, "3.4.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("聖夜讃歌", 41, 175, 188, "3.4.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("ストレイソウル・アラウンド", 171, 150, 133, "3.4.2", 22);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Manifold Hypothesis", 172, 174, 150, "3.4.2", 22);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("K.Moe (VIP)", 173, 174, 130, "3.4.2", 22);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("G.V.N. (Glitter,Vomitus and Neon)", 174, 175, 163, "3.4.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Crush BETA", 175, 200, 133, "3.4.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Broken Sky", 176, 130, 156, "3.5.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("BRAIN HACKER", 177, 158, 122, "3.5.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Xenolith", 178, 170, 147, "3.6.0", 24);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Artificial Existence", 179, 191, 166, "3.6.0", 24);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Indelible Scar", 180, 223, 140, "3.6.0", 24);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Antithese", 181, 172, 144, "3.6.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("PRAGMATISM -RESURRECTION-", 182, 174, 156, "3.6.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Shine After", 183, 170, 165, "3.6.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Bloom", 184, 150, 160, "3.6.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("幽世桔梗", 185, 182, 154, "3.7.0", 25);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("千紫万紅", 186, 203, 144, "3.7.0", 25);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("明鏡烈火", 187, 200, 132, "3.7.0", 25);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("今天不是明天", 188, 125, 171, "3.7.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Cuvism³", 189, 194, 160, "3.8.0", 26);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("iL-Artifact", 190, 184, 163, "3.8.0", 26);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("a truth seeker -Communication with Utopia will be lost-", 191, 206, 122, "3.8.0", 26);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Bounded Quietude", 192, 280, 152, "3.8.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("君往何处 (Quo Vadis)", 193, 160, 133, "3.8.1", 27);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("暗夜苏醒 (REANIMATE)", 194, 174, 156, "3.8.1", 27);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Grimheart", 195, 170, 150, "3.9.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Thrash force", 196, 190, 147, "3.9.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Originally", 197, 200, 141, "3.9.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("黄金之城 (GOLD TOWN)", 198, 160, 127, "3.10.0", 27);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("双重间谍 (Double Agent)", 199, 160, 148, "3.10.0", 27);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("幻影鬼魅 (PLEASE)", 200, 161, 125, "3.10.0", 27);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Schadenfreude", 173, 198, 151, "3.10.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Le temps perdu", 123, 188, 146, "3.10.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Fixations Toward the Stars", 201, 150, 170, "3.10.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("valor\starcross", 202, 175, 159, "3.10.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Comet", 203, 180, 152, "3.10.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("白と黒のバケモノ", 204, 205, 139, "3.10.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Devotion", 205, 167, 158, "3.10.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Kirakira Noel Story!!", 49, 180, 136, "3.10.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Shelter", 206, 170, 139, "3.10.4", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("蝎虎天体 -Lacertid-", 207, 220, 142, "3.10.4", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("インマイマインド", 208, 155, 169, "3.11.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("ニライカナイ (NiraicA_nai Mix)", 209, 130, 152, "3.11.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Swing Skip Drop", 210, 210, 124, "3.11.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("宇宙残骸少女 (Cosmic Dusty Girl)", 211, 140, 135, "3.11.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Resolver", 212, 123, 160, "3.12.0", 28);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Luminous Entities Lost Heart", 213, 200, 167, "3.12.0", 28);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("KIZUNA Resolution", 214, 240, 134, "3.12.0", 28);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("AbsoluTe disoRdeR", 215, 256, 190, "3.12.0", 28);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Aphrodite's Child (short ver.)", 216, 128, 167, "3.13.0", 29);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("DevlAtiOn (short ver.)", 217, 155, 172, "3.13.0", 29);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("NO x", 218, 190, 153, "3.13.0", 29);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Alice in a xxxxxxxx", 219, 144, 155, "3.13.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Radiance", 220, 155, 147, "3.14.0", 30);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Diamond Dust", 221, 200, 155, "3.14.0", 30);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Stardust:RAY", 222, 164, 165, "3.14.0", 30);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Frozen Heart", 41, 185, 192, "3.14.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Helios", 223, 150, 133, "3.14.2", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Flutter Echo", 224, 146, 166, "3.15.0", 16);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Re: birth", 225, 196, 157, "3.15.0", 16);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Avataar ~Reincarnation of Kalpa~", 226, 180, 174, "3.15.0", 16);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("雪降り ~雪が降っている~", 227, 156, 151, "3.15.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Retribution ~ Cycle of Redemption ~", 228, 225, 172, "3.15.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("アンビバレンス", 229, 187, 162, "3.16.0", 31);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Komplexe", 230, 165, 139, "3.16.0", 31);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("sølips", 231, 199, 146, "3.16.0", 31);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("QZKago Requiem", 128, 290, 138, "3.16.0", 31);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("So laggy! (feat. Uzumaki)", 232, 180, 126, "3.16.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("000 -Ain Soph Aur-", 233, 97, 153, "3.16.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Xep+ion", 234, 170, 117, "3.17.0", 32);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Archidoxen", 235, 160, 124, "3.17.0", 32);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("百鬼֎夜行", 236, 200, 138, "3.17.0", 32);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("BANGING STRIKE", 237, 234, 147, "3.17.0", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("The Whole Rest", 238, 157, 140, "3.18.0", 33);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Cristalisia", 239, 134, 135, "3.18.0", 33);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Hydra", 240, 160, 150, "3.18.0", 33);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("最高傑作", 241, 130, 142, "3.18.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Locomotive", 242, 128, 150, "3.18.1", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Alb", 243, 140, 150, "3.18.2", 33);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Incyde", 244, 180, 200, "3.18.2", 33);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("彩", 245, 170, 165, "3.18.2", 33);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("彼方へ、名もなき海辺より", 246, 185, 172, "3.18.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("ABYSS MOTION 192.333", 247, 192, 125, "3.18.3", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Xenophobia", 248, 175, 146, "3.18.4", 1);
INSERT INTO Song (SongName, ComposerId, Bpm, SongLength, AddVersion, ChapterId) VALUES ("Verrückt", 249, 238, 122, "3.18.4", 1);
