INSERT INTO Composer (ComposerName) VALUES ("SunsetRay");
INSERT INTO Composer (ComposerName) VALUES ("Nces");
INSERT INTO Composer (ComposerName) VALUES ("Frums");
INSERT INTO Composer (ComposerName) VALUES ("Likey");
INSERT INTO Composer (ComposerName) VALUES ("CrossingSound");
INSERT INTO Composer (ComposerName) VALUES ("姜米條");
INSERT INTO Composer (ComposerName) VALUES ("Ctymax feat. Nces");
INSERT INTO Composer (ComposerName) VALUES ("Tetrajectory feat. Ctymax");
INSERT INTO Composer (ComposerName) VALUES ("Only My Black Score");
INSERT INTO Composer (ComposerName) VALUES ("MYUKKE.");
INSERT INTO Composer (ComposerName) VALUES ("SOTUI");
INSERT INTO Composer (ComposerName) VALUES ("Bluewind");
INSERT INTO Composer (ComposerName) VALUES ("Normal1zer");
INSERT INTO Composer (ComposerName) VALUES ("SunsetRay/NceS");
INSERT INTO Composer (ComposerName) VALUES ("MonstDeath");
INSERT INTO Composer (ComposerName) VALUES ("Antistar feat. Ctymax");
INSERT INTO Composer (ComposerName) VALUES ("Itsuki");
INSERT INTO Composer (ComposerName) VALUES ("Megalo_PaleWhite");
INSERT INTO Composer (ComposerName) VALUES ("Tanchiky");
INSERT INTO Composer (ComposerName) VALUES ("FLuoRiTe/姜米條");
INSERT INTO Composer (ComposerName) VALUES ("1N6Fs");
INSERT INTO Composer (ComposerName) VALUES ("Ju_E");
INSERT INTO Composer (ComposerName) VALUES ("影虎。");
INSERT INTO Composer (ComposerName) VALUES ("rider");
INSERT INTO Composer (ComposerName) VALUES ("姜米條☆颶風~♫元力上人♫");
INSERT INTO Composer (ComposerName) VALUES ("P4koo feat. つゆり花鈴");
INSERT INTO Composer (ComposerName) VALUES ("dandeless");
INSERT INTO Composer (ComposerName) VALUES ("Se-U-Ra");
INSERT INTO Composer (ComposerName) VALUES ("WyvernP");
INSERT INTO Composer (ComposerName) VALUES ("Hundotte");
INSERT INTO Composer (ComposerName) VALUES ("P4koo");
INSERT INTO Composer (ComposerName) VALUES ("Lime");
INSERT INTO Composer (ComposerName) VALUES ("Team Grimoire");
INSERT INTO Composer (ComposerName) VALUES ("LandRoot");
INSERT INTO Composer (ComposerName) VALUES ("Attoclef");
INSERT INTO Composer (ComposerName) VALUES ("米虾Fomiki & 初云CLoudie");
INSERT INTO Composer (ComposerName) VALUES ("nm-y & Kry.exe");
INSERT INTO Composer (ComposerName) VALUES ("Normal1zer vs. Broken Nerdz");
INSERT INTO Composer (ComposerName) VALUES ("Sakuzyo");
INSERT INTO Composer (ComposerName) VALUES ("1112 vs. Star＊");
INSERT INTO Composer (ComposerName) VALUES ("A-39/沙包P");
INSERT INTO Composer (ComposerName) VALUES ("Rinth_live");
INSERT INTO Composer (ComposerName) VALUES ("Dachs");
INSERT INTO Composer (ComposerName) VALUES ("ユメミド");
INSERT INTO Composer (ComposerName) VALUES ("Rabpit");
INSERT INTO Composer (ComposerName) VALUES ("Forged Reigns");
INSERT INTO Composer (ComposerName) VALUES ("kanoryo");
INSERT INTO Composer (ComposerName) VALUES ("S9ryne");
INSERT INTO Composer (ComposerName) VALUES ("Reku Mochizuki");
INSERT INTO Composer (ComposerName) VALUES ("Dolphin");
INSERT INTO Composer (ComposerName) VALUES ("D_AAN");
INSERT INTO Composer (ComposerName) VALUES ("Jehezukiel + KURORAK");
INSERT INTO Composer (ComposerName) VALUES ("DJ SHION.Y");
INSERT INTO Composer (ComposerName) VALUES ("uma vs. モリモリあつし");
INSERT INTO Composer (ComposerName) VALUES ("Ardolf");
INSERT INTO Composer (ComposerName) VALUES ("わかどり");
INSERT INTO Composer (ComposerName) VALUES ("rareguy & Reina");
INSERT INTO Composer (ComposerName) VALUES ("Ωμεγα");
INSERT INTO Composer (ComposerName) VALUES ("LeaF");
INSERT INTO Composer (ComposerName) VALUES ("闫东炜");
INSERT INTO Composer (ComposerName) VALUES ("YUE.STEVEN/uen");
INSERT INTO Composer (ComposerName) VALUES ("小红Akane, 李祥晖");
INSERT INTO Composer (ComposerName) VALUES ("符白牙/SiYFics");
INSERT INTO Composer (ComposerName) VALUES ("Asuka");
INSERT INTO Composer (ComposerName) VALUES ("Friedwav");
INSERT INTO Composer (ComposerName) VALUES ("K-forest");
INSERT INTO Composer (ComposerName) VALUES ("朔(Apo11o program vs. お月さま交響曲) ft. kuroa* × 荒巻");
INSERT INTO Composer (ComposerName) VALUES ("Halv");
INSERT INTO Composer (ComposerName) VALUES ("SaMZIng");
INSERT INTO Composer (ComposerName) VALUES ("Ctymax vs. NceS");
INSERT INTO Composer (ComposerName) VALUES ("Neutral Moon");
INSERT INTO Composer (ComposerName) VALUES ("rareguy");
INSERT INTO Composer (ComposerName) VALUES ("BilliumMoto");
INSERT INTO Composer (ComposerName) VALUES ("lixound");
INSERT INTO Composer (ComposerName) VALUES ("黒皇帝");
INSERT INTO Composer (ComposerName) VALUES ("Sound Souler");
INSERT INTO Composer (ComposerName) VALUES ("HyuN");
INSERT INTO Composer (ComposerName) VALUES ("HyuN feat. YURI");
INSERT INTO Composer (ComposerName) VALUES ("HyuN feat. Syepias");
INSERT INTO Composer (ComposerName) VALUES ("DarTokki");
INSERT INTO Composer (ComposerName) VALUES ("EmoCo.");
INSERT INTO Composer (ComposerName) VALUES ("CAP3");
INSERT INTO Composer (ComposerName) VALUES ("WyvernP feat. Madol");
INSERT INTO Composer (ComposerName) VALUES ("EBIMAYO");
INSERT INTO Composer (ComposerName) VALUES ("Paul Bazooka");
INSERT INTO Composer (ComposerName) VALUES ("tokiwa");
INSERT INTO Composer (ComposerName) VALUES ('ZxNX as "Delaina"');
INSERT INTO Composer (ComposerName) VALUES ("Tetrajectory");
INSERT INTO Composer (ComposerName) VALUES ("Quree");
INSERT INTO Composer (ComposerName) VALUES ("ElousΛ.-FZ");
INSERT INTO Composer (ComposerName) VALUES ("Kry.exe");
INSERT INTO Composer (ComposerName) VALUES ("EnFr");
INSERT INTO Composer (ComposerName) VALUES ("Grand Thaw / Rigël Theatre");
INSERT INTO Composer (ComposerName) VALUES ("MALVA.");
INSERT INTO Composer (ComposerName) VALUES ("A-39");
INSERT INTO Composer (ComposerName) VALUES ("SCTL");
INSERT INTO Composer (ComposerName) VALUES ("PTB10");
INSERT INTO Composer (ComposerName) VALUES ("adaptor vs DRIVE.");
INSERT INTO Composer (ComposerName) VALUES ("Fl00t");
INSERT INTO Composer (ComposerName) VALUES ("iF");
INSERT INTO Composer (ComposerName) VALUES ("kozato snow");
INSERT INTO Composer (ComposerName) VALUES ("DETRO a.k.a. ルゼ");
INSERT INTO Composer (ComposerName) VALUES ("ルゼ");
INSERT INTO Composer (ComposerName) VALUES ("ginkiha");
INSERT INTO Composer (ComposerName) VALUES ("USAO");
INSERT INTO Composer (ComposerName) VALUES ("Cashew");
INSERT INTO Composer (ComposerName) VALUES ("Joulez");
INSERT INTO Composer (ComposerName) VALUES ("Z ClaxX & SumailLight");
INSERT INTO Composer (ComposerName) VALUES ("椒盐菠萝");
INSERT INTO Composer (ComposerName) VALUES ("KAH");
INSERT INTO Composer (ComposerName) VALUES ("Silentroom");
INSERT INTO Composer (ComposerName) VALUES ("Sera Amagi");
INSERT INTO Composer (ComposerName) VALUES ("Zris");
INSERT INTO Composer (ComposerName) VALUES ("siqlo");
INSERT INTO Composer (ComposerName) VALUES ("HyuN & KLYDIX");
INSERT INTO Composer (ComposerName) VALUES ("Limpid");
INSERT INTO Composer (ComposerName) VALUES ("HAMA");
INSERT INTO Composer (ComposerName) VALUES ("ぐるたみん");
INSERT INTO Composer (ComposerName) VALUES ("z1on & kyrrin");
INSERT INTO Composer (ComposerName) VALUES ("Justin Dai");
INSERT INTO Composer (ComposerName) VALUES ("李化禹");
INSERT INTO Composer (ComposerName) VALUES ("Ray Nautica & Reku Mochizuki");
INSERT INTO Composer (ComposerName) VALUES ("Daison");
INSERT INTO Composer (ComposerName) VALUES ("TangJuan");
INSERT INTO Composer (ComposerName) VALUES ("rN");
INSERT INTO Composer (ComposerName) VALUES ("アリスシャッハと魔法の楽団");
INSERT INTO Composer (ComposerName) VALUES ("Nothing But Requiem feat. Aikapin & Chiyoko");
INSERT INTO Composer (ComposerName) VALUES ("t+pazolite");
INSERT INTO Composer (ComposerName) VALUES ("Maozon");
INSERT INTO Composer (ComposerName) VALUES ("U-ske feat. 棗いつき");
INSERT INTO Composer (ComposerName) VALUES ("月見静華 vs. LUNARiUM");
INSERT INTO Composer (ComposerName) VALUES ("ETIA. Feat. Jenga");
INSERT INTO Composer (ComposerName) VALUES ("Cosmograph");
INSERT INTO Composer (ComposerName) VALUES ("姜米條 & SumaiLight");
INSERT INTO Composer (ComposerName) VALUES ("Aoi");
INSERT INTO Composer (ComposerName) VALUES ("Turquoise(DRIVE.+Nota)");
INSERT INTO Composer (ComposerName) VALUES ("茶鸣拾贰律");
INSERT INTO Composer (ComposerName) VALUES ("Abyss Idols");
INSERT INTO Composer (ComposerName) VALUES ("Plastic Fruits");
INSERT INTO Composer (ComposerName) VALUES ("Scaler & Mestie & 果丸哒呦");
INSERT INTO Composer (ComposerName) VALUES ("VeetaCrush vs. [itsu(feat.itsu)]");
INSERT INTO Composer (ComposerName) VALUES ("BLACK 0");
INSERT INTO Composer (ComposerName) VALUES ("Ponchi♪ feat. はぁち");
INSERT INTO Composer (ComposerName) VALUES ("Iriss-Frantzz");
INSERT INTO Composer (ComposerName) VALUES ("Sobrem × Silentroom");
INSERT INTO Composer (ComposerName) VALUES ("seatrus");
INSERT INTO Composer (ComposerName) VALUES ("Roy Mikelate");
INSERT INTO Composer (ComposerName) VALUES ("Jade");
INSERT INTO Composer (ComposerName) VALUES ("Pica & M2U");
INSERT INTO Composer (ComposerName) VALUES ("Θ");
INSERT INTO Composer (ComposerName) VALUES ("litmus*");
INSERT INTO Composer (ComposerName) VALUES ("Lure Rabbit & V!C");
INSERT INTO Composer (ComposerName) VALUES ("Rabbit House");
INSERT INTO Composer (ComposerName) VALUES ("Yesod");
INSERT INTO Composer (ComposerName) VALUES ("BelieverInYou(阿卡姆巫师)");
INSERT INTO Composer (ComposerName) VALUES ("Hinkik & Himitsu");
INSERT INTO Composer (ComposerName) VALUES ("ころねぽち With 立秋");
INSERT INTO Composer (ComposerName) VALUES ("typeMARS");
INSERT INTO Composer (ComposerName) VALUES ("かめりあ");
INSERT INTO Composer (ComposerName) VALUES ("SYNTHETIC");
INSERT INTO Composer (ComposerName) VALUES ("imvi");
INSERT INTO Composer (ComposerName) VALUES ("NIWASHI");
INSERT INTO Composer (ComposerName) VALUES ("DJ Raisei");
INSERT INTO Composer (ComposerName) VALUES ("Iris");
INSERT INTO Composer (ComposerName) VALUES ("Yooh");
INSERT INTO Composer (ComposerName) VALUES ("ARForest");
INSERT INTO Composer (ComposerName) VALUES ("Feryquitous feat.藍月なくる");
INSERT INTO Composer (ComposerName) VALUES ("PRASTIK DANCEFLOOR");
INSERT INTO Composer (ComposerName) VALUES ("光吉猛修 VS 穴山大輔 VS Kai VS 水野健治 VS 大国奏音");
INSERT INTO Composer (ComposerName) VALUES ("DingerBox");
INSERT INTO Composer (ComposerName) VALUES ("みーに");
INSERT INTO Composer (ComposerName) VALUES ("cybermiso feat. tigerlily");
INSERT INTO Composer (ComposerName) VALUES ("ZxNX");
INSERT INTO Composer (ComposerName) VALUES ("Salty Salt & Unfold33");
INSERT INTO Composer (ComposerName) VALUES ("shadow_bling");
INSERT INTO Composer (ComposerName) VALUES ("Jungo & MAX 3 feat. 刘佳宜Snow & 幻影刃shadow");
INSERT INTO Composer (ComposerName) VALUES ("SOMON");
INSERT INTO Composer (ComposerName) VALUES ("Tatsh");
INSERT INTO Composer (ComposerName) VALUES ("Jun Kuroda");
INSERT INTO Composer (ComposerName) VALUES ("Noah");
INSERT INTO Composer (ComposerName) VALUES ("Blacklolita");
INSERT INTO Composer (ComposerName) VALUES ("Laur");
INSERT INTO Composer (ComposerName) VALUES ("Adean & JocularACE");
INSERT INTO Composer (ComposerName) VALUES ("targ & 麻团qwq");
INSERT INTO Composer (ComposerName) VALUES ("Capchii feat. まるもこ");
INSERT INTO Composer (ComposerName) VALUES ("r0y vs. WABI");
INSERT INTO Composer (ComposerName) VALUES ("M-UE vs. Reku Mochizuki");
INSERT INTO Composer (ComposerName) VALUES ("PIKASONIC feat. 兰音Reine");
INSERT INTO Composer (ComposerName) VALUES ("Fl00t vs Halv");
INSERT INTO Composer (ComposerName) VALUES ('Link"0');
INSERT INTO Composer (ComposerName) VALUES ("kuro");
INSERT INTO Composer (ComposerName) VALUES ("Finite Limit vs SiLiS");
INSERT INTO Composer (ComposerName) VALUES ("M2U");
INSERT INTO Composer (ComposerName) VALUES ("Warak");
INSERT INTO Composer (ComposerName) VALUES ("Puru");
INSERT INTO Composer (ComposerName) VALUES ("KAH vs. E0ri4");
INSERT INTO Composer (ComposerName) VALUES ("SNKS & Mizku");
INSERT INTO Composer (ComposerName) VALUES ("MEMME");
INSERT INTO Composer (ComposerName) VALUES ("Wav.AV");
INSERT INTO Composer (ComposerName) VALUES ("R300K");
INSERT INTO Composer (ComposerName) VALUES ("Foodbot");
INSERT INTO Composer (ComposerName) VALUES ("Lundy vs. Wyvren");
INSERT INTO Composer (ComposerName) VALUES ("CNHKSS feat. 符白牙");
INSERT INTO Composer (ComposerName) VALUES ("テヅカ");
INSERT INTO Composer (ComposerName) VALUES ("Connexio");
INSERT INTO Composer (ComposerName) VALUES ("MeatyRabbit & NceS");
INSERT INTO Composer (ComposerName) VALUES ("Cream & Daily天利");
INSERT INTO Composer (ComposerName) VALUES ("レシオP");
INSERT INTO Composer (ComposerName) VALUES ("roop from STR");
INSERT INTO Composer (ComposerName) VALUES ("ミハイル");
INSERT INTO Composer (ComposerName) VALUES ("辻原一郎");
INSERT INTO Composer (ComposerName) VALUES ("Gomadare");
INSERT INTO Composer (ComposerName) VALUES ("NormalM feat. Usagi Denki");
INSERT INTO Composer (ComposerName) VALUES ("TAG");
INSERT INTO Composer (ComposerName) VALUES ("Acute Disarray");
INSERT INTO Composer (ComposerName) VALUES ("RUQOA");
INSERT INTO Composer (ComposerName) VALUES ("polysha");
INSERT INTO Composer (ComposerName) VALUES ("Juggernaut.");
INSERT INTO Composer (ComposerName) VALUES ("Nagiha");
INSERT INTO Composer (ComposerName) VALUES ("Nhato");
INSERT INTO Composer (ComposerName) VALUES ('Masahiro "Godspeed" Aoki');
INSERT INTO Composer (ComposerName) VALUES ("kanone vs. BlackY");
INSERT INTO Composer (ComposerName) VALUES ("NOA(Cortrix) & BotaNya");
INSERT INTO Composer (ComposerName) VALUES ("Cansol");
INSERT INTO Composer (ComposerName) VALUES ("ああああ");
INSERT INTO Composer (ComposerName) VALUES ("Scarlette a.k.a CrYmson");
INSERT INTO Composer (ComposerName) VALUES ("AiSS w/ 夜輪 ft. 結月ゆかり");
INSERT INTO Composer (ComposerName) VALUES ("Ardolf vs. Daily天利");
INSERT INTO Composer (ComposerName) VALUES ("すりぃ×相沢");
INSERT INTO Composer (ComposerName) VALUES ("雄之助 feat. Sennzai");
INSERT INTO Composer (ComposerName) VALUES ("rintaro soma");
INSERT INTO Composer (ComposerName) VALUES ("ShrimpCats.(はぁち×後藤涼舗)");
INSERT INTO Composer (ComposerName) VALUES ("Yumeji");
INSERT INTO Composer (ComposerName) VALUES ("Acotto");
INSERT INTO Composer (ComposerName) VALUES ("Se_IRA");
INSERT INTO Composer (ComposerName) VALUES ("Salad Savior");
INSERT INTO Composer (ComposerName) VALUES ("Dew Pleiades");
INSERT INTO Composer (ComposerName) VALUES ("KIVΛ");
INSERT INTO Composer (ComposerName) VALUES ("onoken");
INSERT INTO Composer (ComposerName) VALUES ("James Landino X Akira Complex");
INSERT INTO Composer (ComposerName) VALUES ("PYKAMIA");
INSERT INTO Composer (ComposerName) VALUES ("♠︎K");
INSERT INTO Composer (ComposerName) VALUES ("Avans");
INSERT INTO Composer (ComposerName) VALUES ("YbeLL");
INSERT INTO Composer (ComposerName) VALUES ("MisoilePunch♪");
INSERT INTO Composer (ComposerName) VALUES ("打打だいず&月乃");
INSERT INTO Composer (ComposerName) VALUES ("ariiol & 奏Sou");
INSERT INTO Composer (ComposerName) VALUES ("XinG");
INSERT INTO Composer (ComposerName) VALUES ("Raimukun");
